export const GET_ATM_DATA = 'GET_ATM_DATA'; 
export const GOOGLE_LOCATION_SEARCH = 'GOOGLE_LOCATION_SEARCH';
export const GETTING_ALIPAY_IMAGE = 'GETTING_ALIPAY_IMAGE';
export const OPEN_CLOSE_MODAL = 'OPEN_CLOSE_MODAL';